### PR TITLE
Bump cdap version to 6.7.3 snapshot

### PR DESCRIPTION
**Pull request by sumitjnn**
- [x] To be merged after cdap-build for 6.7.3-SNAPSHOT is created.
https://github.com/cdapio/cdap-build/releases/tag/v6.7.3-SNAPSHOT

### CODE REVIEW

**Review by itsankit-google — APPROVED** [review]

**Comment by sumitjnn** [comment]
Validated that [scenario](https://github.com/data-integrations/google-cloud/blob/release/0.20/src/e2e-test/features/gcs/source/GCSSourceError.feature#L39) failing in the [build](https://github.com/cdapio/cdap-e2e-tests/actions/runs/3985201468/jobs/6832289814) is working for me with 6.7.3 sandbox on local. 

Looks like a flaky test, running another build.

**Comment by itsankit-google** [comment]
Please also change the version in this script - https://github.com/cdapio/cdap-e2e-tests/blob/2b21dd2b64ffe2801669968b6ec960fde74b85dc/src/main/scripts/run_e2e_test_module.py#L32

**Comment by sumitjnn** [comment]
> Please also change the version in this script -
> 
> https://github.com/cdapio/cdap-e2e-tests/blob/2b21dd2b64ffe2801669968b6ec960fde74b85dc/src/main/scripts/run_e2e_test_module.py#L32

- Are we still using https://builds.cask.co ? OR should it be changed to github link?
- Is run_e2e_test_module.py used anywhere?

**Comment by itsankit-google** [comment]
> > Please also change the version in this script -
> > https://github.com/cdapio/cdap-e2e-tests/blob/2b21dd2b64ffe2801669968b6ec960fde74b85dc/src/main/scripts/run_e2e_test_module.py#L32
> 
> * Are we still using https://builds.cask.co ? OR should it be changed to github link?
> * Is run_e2e_test_module.py used anywhere?

It should be changed to github link, not sure if this script is used anywhere.

**Pull request merged**
