### PR TITLE
Config ProjectID parameter

### PR DESCRIPTION
**Pull request by ksahilCF**
Project parameter is not hardcoded and made configurable.

### CODE REVIEW

**Review by tivv — COMMENTED** [review]
Why are you dropping selenium driver in this pr?

**Comment by ksahilCF** [comment]
This is not the path from where we are setting the executable path. This path is updated in executable OS PR

**Comment by rmstar** [comment]
Please only include relevant changes in the PR - this PR is for making project id configurable. Also, please resolve conflicts on the branch.

**Comment by ksahilCF** [comment]
Same function change for making project parameter configurable. Please merge the PLUGIN-787 branch then only i can raise this request.

**Pull request closed without merging**
